### ISSUE TITLE
Unable to install on Eclipse 4.9

### ISSUE THREAD

**Issue by nolddor** [masrawi/veloeclipse#4]
It seems Eclipse cannot connect to the repository and install Veloeclipse 3.0.1.
Could you check?

**Comment by masrawi** [comment]
can you try 
```
https://github.com/masrawi/veloeclipse/raw/master/
```

 as update site and see if it works?

**Comment by nolddor** [comment]
Don't should work w/o doing this? I mean if I search **veloeclipse** using **Eclipse Marketplace** I must be able to install the complement but it doesn't work at all.

Do you need to update any URL on your side? I suppose other people is getting the same error as I.

See:
![imagen](https://user-images.githubusercontent.com/1280022/60772021-4d3dc600-a0f0-11e9-9342-0b3b465402ef.png)

**Comment by masrawi** [comment]
I updated the url on Eclipse Marketplace

**Comment by nolddor** [comment]
The problem seems to be the same with the new URL.
See:
![imagen](https://user-images.githubusercontent.com/1280022/60916716-69c43480-a28f-11e9-8bb0-26e68171e50b.png)

...and after press Yes button:
![imagen](https://user-images.githubusercontent.com/1280022/60916851-c889ae00-a28f-11e9-85af-ef6eea336852.png)


**EDIT**
Following trace is written in the dialog:
`The following solutions are not available: veloeclipse 3.0.1 (id=3.0.1.feature.group, site=https://github.com/masrawi/veloeclipse/raw/master/)`

This can be find on eclipse log file:
```
!ENTRY org.eclipse.equinox.p2.repository 2 0 2019-07-09 21:25:48.696
!MESSAGE Server returned lastModified <= 0 for https://github.com/masrawi/veloeclipse/raw/master/content.jar
```

**Comment by masrawi** [comment]
it seems they changed some settings in the marketplace. can you please try again? I changed some settings

**Comment by nolddor** [comment]
It works now ;)

Thanks for your kind support <3
